db_ts_diff <- diff(db_ts, lag=12)
plot(db$`Telefonia Móvel`, type="l")
plot(db_ts)
plot(db_ts_diff)
ajuste_sazonal_dados <- db_ts-db_ts_diff
plot(ajuste_sazonal_dados)
treinamento_ts_diff <-  window(db_ts_diff, start=c(2015, 1), end=c(2019,7))
validacao_ts_diff <- window(db_ts_diff, start=c(2019, 8), end=c(2021,3))
summary(ur.kpss(treinamento_ts_diff))
summary(ur.df(treinamento_ts_diff))
Acf(treinamento_ts_diff)
Pacf(treinamento_ts_diff)
modelo_arima <- Arima(treinamento_ts_diff, order = c(2,1,1))
summary(modelo_arima)
modelo_arima_proj <- forecast(modelo_arima, h=55, level=0.95)
plot(modelo_arima_proj, ylab="Despesas", xlab="Tempo", bty="l", xaxt="n", xlim=c(2015,2019.55), flty=2)
axis(1, at=seq(2015, 2019, 7), labels=format(seq(2015, 2019, 7)))

lines(modelo_arima$fitted, lwd=2, col="blue")

lines(validacao_ts_diff)
checkresiduals(modelo_arima_proj, test="LB")
accuracy(modelo_arima_proj, validacao_ts_diff)
auto.arima(treinamento_ts_diff, seasonal = FALSE, stepwise=FALSE, approximation = FALSE)
